name: MacPorts Bump
description: Bump MacPorts Portfile
author: harens
branding:
  icon: 'command'  
  color: 'white'
inputs:
  token:
    description: GitHub token
    required: true
  name:
    description: |
      Name of the port
      Example: py-questionary
    required: true
  tag:
    description: |
      Git tag or version number
      Example: v2.3.4
    required: false
    default: ${{github.ref}}
  repo:
    description: |
      Portfile repo to modify
    required: false
    default: macports/macports-ports
runs:
  using: composite
  steps:
    - run: . scripts/main.sh
      shell: bash
      env:
        TAG: ${{inputs.tag}}
        TOKEN: ${{inputs.TOKEN}}
        NAME: ${{inputs.name}}
        REPO: ${{inputs.repo}}
