name: MacPorts Bump
description: Bump MacPorts Portfile
author: harens
branding:
  icon: 'command'  
  color: 'white'
inputs:
  token:
    description: GitHub token
    required: true
  name:
    description: |
      Name of the port
      Example: py-questionary
    required: true
  user:
     description: |
       Name of user initialising the action
     required: false
     default: ${{github.actor}}
runs:
  using: composite
  steps:
    - run: . scripts/main.sh
      shell: bash
      env:
        TOKEN: ${{inputs.TOKEN}}
        NAME: ${{inputs.name}}
        GITHUB_USER: ${{inputs.user}}
