name: Test

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md
  workflow_dispatch:

jobs:
  test:
    name: Test MacPorts Bump Action
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test GitHub Action
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          name: glide
          tag: v0.13.3
