name: Test

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - README.md

jobs:
  test:
    name: Test MacPorts Bump Action
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test GitHub Action
        uses: ./
        with:
          token: ${{secrets.TOKEN}}
          name: py-questionary
          tag: v1.7.1
          package: true
      - uses: actions/upload-artifact@v2
        with:
          name: Binary File
          path: ${{ github.workspace }}/packages/*
